### ISSUE TITLE
Block update to UV variables

### ISSUE THREAD

**Issue by dsberman** [xinabox/pxt-SL01#5]
![Screen Shot 2020-03-09 at 15 49 43](https://user-images.githubusercontent.com/45306727/77074013-cf5ce900-69f8-11ea-8776-f80a0b9d5bf8.png)

Should show UV index only, rather than A and B detail

**Comment by gotfredsen** [comment]
@lb, the new SL01 doesn't have UVA and UVB, so we don't want to get users used to the idea they can UVA/UVB. Please only allow UV Index.
